site_name: Packaging and publishing python software for research
repo_url: https://github.com/acceleratescience/packaging-publishing
site_url: https://acceleratescience.github.io/packaging-publishing/
nav:
  - Home: 
    - index.md
    - License: Home/LICENSE.md
    - About us: Home/About.md
  - Setting up: 1_setting_up.md
  - Project overview: 2_project_overview.md
  - Poetry: 3_poetry.md
  - Testing: 4_Testing.md
  - Publishing:
    - Publishing to PyPI: publishing_docs/publishing.md
    - Making Documentation: publishing_docs/documentation.md
  - CI/CD:
    - CICD/index.md
    - Pre-commits: CICD/precommit.md
    - Testing: CICD/testing.md
    - Publishing: CICD/publishing.md
    - Documentation: CICD/documentation.md
theme:
  favicon: imgs/trace.svg
  name: material
  logo: imgs/trace.svg
  features:
    - search.suggest
    - search.highlight
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    annotation: material/chevron-right-circle 
plugins:
  - mkdocstrings
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
watch:
  - .
